### PR TITLE
Support more RecordTypes

### PR DESCRIPTION
**Pull request by T-Ralph**
BodyFat, BodyTemperature, HeartRateSeries, OxygenSaturation, RespiratoryRate, and RestingHeartRate.

@yukukotani Please, take a look at this.
Thank you.

### CODE REVIEW

**Comment by T-Ralph** [comment]
Hello @yukukotani 
If you have some time, kindly, take a look at this.
Thank you.

**Review by yukukotani — APPROVED** [review]
Sorry for the late review, thanks!

**Comment by yukukotani** [comment]
FYI: You can automatically update README.md by `pnpm docgen`

**Comment by yukukotani** [comment]
Released in [v0.7.0](https://github.com/ubie-oss/capacitor-health-connect/releases/tag/v0.7.0)

**Comment by T-Ralph** [comment]
Thank you, @yukukotani

**Pull request merged**
